CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'Products') THEN
        CREATE SCHEMA "Products";
    END IF;
END $EF$;

CREATE TABLE "Products"."Products" (
    "ProductId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(256) NOT NULL,
    "Description" character varying(256) NOT NULL,
    "Price" numeric(18,2) NOT NULL,
    "Category" text NOT NULL,
    "StockLevel" integer NOT NULL,
    CONSTRAINT "PK_Products" PRIMARY KEY ("ProductId")
);

CREATE TABLE "Products"."Sales" (
    "SaleId" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProductId" integer NOT NULL,
    "QuantitySold" integer NOT NULL,
    "SaleDate" timestamp with time zone NOT NULL,
    "TotalSaleAmount" numeric(18,2) NOT NULL,
    CONSTRAINT "PK_Sales" PRIMARY KEY ("SaleId"),
    CONSTRAINT "FK_Sales_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products"."Products" ("ProductId") ON DELETE CASCADE
);

CREATE INDEX "IX_Products_Category" ON "Products"."Products" ("Category");

CREATE INDEX "IX_Sales_ProductId" ON "Products"."Sales" ("ProductId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240427193511_CreatedProductsSchema', '7.0.18');

COMMIT;

START TRANSACTION;

ALTER TABLE "Products"."Sales" ADD "CustomerId" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240427201922_AddedCustomerId', '7.0.18');

COMMIT;

START TRANSACTION;

ALTER TABLE "Products"."Sales" ADD "CancelDate" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "Products"."Sales" ADD "Status" character varying(256) NOT NULL DEFAULT '';

ALTER TABLE "Products"."Products" ALTER COLUMN "Category" TYPE integer;

ALTER TABLE "Products"."Products" ADD "Brand" text NOT NULL DEFAULT '';

ALTER TABLE "Products"."Products" ADD "Condition" integer NOT NULL DEFAULT 0;

ALTER TABLE "Products"."Products" ADD "GraphicsCard" text NULL;

ALTER TABLE "Products"."Products" ADD "ProcessorType" text NULL;

ALTER TABLE "Products"."Products" ADD "RAM" integer NULL;

ALTER TABLE "Products"."Products" ADD "ScreenSize" double precision NULL;

ALTER TABLE "Products"."Products" ADD "Series" text NULL;

ALTER TABLE "Products"."Products" ADD "Storage" integer NULL;

ALTER TABLE "Products"."Products" ADD "StorageType" text NULL;

ALTER TABLE "Products"."Products" ADD "TouchScreen" boolean NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240428124655_AddedLaptopDetailsToProduct', '7.0.18');

COMMIT;

START TRANSACTION;

ALTER TABLE "Products"."Products" ADD "Image" bytea NOT NULL DEFAULT BYTEA E'\\x';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240428125849_ImageStorage', '7.0.18');

COMMIT;

START TRANSACTION;

ALTER TABLE "Products"."Products" ALTER COLUMN "Image" TYPE text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240428132333_UpdateImageColumnToString', '7.0.18');

COMMIT;

START TRANSACTION;

CREATE TABLE "Products"."Baskets" (
    "BasketId" uuid NOT NULL,
    "CustomerId" uuid NOT NULL,
    CONSTRAINT "PK_Baskets" PRIMARY KEY ("BasketId")
);

CREATE TABLE "Products"."BasketItems" (
    "BasketItemId" integer GENERATED BY DEFAULT AS IDENTITY,
    "BasketId" uuid NOT NULL,
    "ProductId" integer NOT NULL,
    "Quantity" integer NOT NULL,
    CONSTRAINT "PK_BasketItems" PRIMARY KEY ("BasketItemId"),
    CONSTRAINT "FK_BasketItems_Baskets_BasketId" FOREIGN KEY ("BasketId") REFERENCES "Products"."Baskets" ("BasketId") ON DELETE CASCADE,
    CONSTRAINT "FK_BasketItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products"."Products" ("ProductId") ON DELETE CASCADE
);

CREATE INDEX "IX_BasketItems_BasketId" ON "Products"."BasketItems" ("BasketId");

CREATE INDEX "IX_BasketItems_ProductId" ON "Products"."BasketItems" ("ProductId");

CREATE UNIQUE INDEX "IX_Baskets_CustomerId" ON "Products"."Baskets" ("CustomerId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240428231747_AddBasket', '7.0.18');

COMMIT;

START TRANSACTION;

ALTER TABLE "Products"."Sales" DROP CONSTRAINT "FK_Sales_Products_ProductId";

DROP INDEX "Products"."IX_Baskets_CustomerId";

ALTER TABLE "Products"."Sales" DROP COLUMN "CancelDate";

ALTER TABLE "Products"."Sales" DROP COLUMN "QuantitySold";

ALTER TABLE "Products"."Sales" ALTER COLUMN "ProductId" DROP NOT NULL;

ALTER TABLE "Products"."Sales" ADD "BasketId" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';

ALTER TABLE "Products"."Baskets" ADD "Status" integer NOT NULL DEFAULT 0;

CREATE UNIQUE INDEX "IX_Sales_BasketId" ON "Products"."Sales" ("BasketId");

ALTER TABLE "Products"."Sales" ADD CONSTRAINT "FK_Sales_Baskets_BasketId" FOREIGN KEY ("BasketId") REFERENCES "Products"."Baskets" ("BasketId") ON DELETE RESTRICT;

ALTER TABLE "Products"."Sales" ADD CONSTRAINT "FK_Sales_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products"."Products" ("ProductId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240429191732_RefinedBasketsandAndsaleTables', '7.0.18');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240507130419_missingstuff', '7.0.18');

COMMIT;

