# This Docker Compose file provisions a local development environment tailored for testing application releases.

version: "3.9"
services:
  # Seq: Provides structured logging. Accessible at http://localhost:5341/
  seq:
    image: "datalust/seq:latest"
    ports: 
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
  
  # Zipkin: Offers distributed tracing. After starting, visit http://localhost:9411/zipkin/ and click 'run query' to view traces
  zipkin:
    image: "openzipkin/zipkin-slim"
    ports:
      - 9411:9411

  # Prometheus: System monitoring and alerting. Accessible at http://localhost:9090/
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
  
  # Grafana: Interactive visualization and analytics platform. Accessible at http://localhost:3000/ Login using the username: admin Passowrd: admin / password
  grafana:
    image: grafana/grafana:8.0.6
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus

  # PostgreSQL: Database service
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=test-tech-shop
      - POSTGRES_USER=techshopuser
      - POSTGRES_PASSWORD=techshoppassword
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d

  # This auto updates the database to match the most upto data configurations 
  migrations:
    build:
      context: ../application_code/src/
      dockerfile: Services/Project.Tech.Shop.Web.Services.Migrations.Startup/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=test-tech-shop;Username=techshopuser;Password=techshoppassword
    depends_on:
      - postgres

  # project_tech_shop_web: find this on 8080
  project_tech_shop_web:
    build:
      context: ../application_code/src/
      dockerfile: Host Applications/Project.Tech.Shop.Web/Dockerfile
    ports:
      - "5045:8080" # Change the left value if port 8080 is already in use
    depends_on:
      - seq
      - zipkin
      - prometheus
      - grafana
      - postgres
      - migrations 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=test-tech-shop;Username=techshopuser;Password=techshoppassword
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
      - SeqEndpoint=http://seq:80
      - Serilog__WriteTo__2__Name=Seq
      - Serilog__WriteTo__2__Args__ServerUrl=http://seq:80
      - Serilog__WriteTo__2__Args__RestrictedToMinimumLevel=Debug
    volumes:
      - data_protection_keys:/root/.aspnet/DataProtection-Keys


volumes:
  data_protection_keys:
  prometheus_data:
  grafana-storage:
  postgres_data: