# This Docker Compose file provisions a local development environment tailored for testing application releases.

version: "3.9"
services:
  # Seq: Provides structured logging. Accessible at http://localhost:5341/
  seq:
    image: "datalust/seq:latest"
    ports: 
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
  
  # Zipkin: Offers distributed tracing. After starting, visit http://localhost:9411/zipkin/ and click 'run query' to view traces
  zipkin:
    image: "openzipkin/zipkin-slim"
    ports:
      - 9411:9411

  # Prometheus: System monitoring and alerting. Accessible at http://localhost:9090/
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
  
  # Grafana: Interactive visualization and analytics platform. Accessible at http://localhost:3000/ Login using the username: admin Passowrd: admin / password
  grafana:
    image: grafana/grafana:8.0.6
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus

  # project_tech_shop_web: find this on 8080
  project_tech_shop_web:
    build:
      context: ../application_code/src/Host Applications/Project.Tech.Shop.Web
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Change the left value if port 8080 is already in use
    depends_on:
      - seq
      - zipkin
      - prometheus
      - grafana

volumes:
  prometheus_data:
  grafana-storage: