global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'crytpo-analysis-ui'
    metrics_path: '/metrics'  # Define the metrics path globally for all targets
    static_configs:
      - targets: ['crytpo-analysis-ui:8080']  # Here, only specify the hostnames

  - job_name: 'crytpo-analysis-backend'
    metrics_path: '/metrics'  # Define the metrics path globally for all targets
    static_configs:
      - targets: ['crytpo-analysis-backend:8080']  # Here, only specify the hostnames

