global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'project_tech_shop'
    metrics_path: '/metrics'  # Define the metrics path globally for all targets
    static_configs:
      - targets: ['project_tech_shop_web:8080']  # Here, only specify the hostnames

